ALTER TABLE public.profiles 
  ADD COLUMN IF NOT EXISTS hustle_name TEXT,
  ADD COLUMN IF NOT EXISTS primary_skill TEXT,
  ADD COLUMN IF NOT EXISTS secondary_skills TEXT[],
  ADD COLUMN IF NOT EXISTS is_hustler BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rating_average NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS has_reviews BOOLEAN DEFAULT false;
